permissions:
  id-token: write
  contents: read

name: Terraform Apply
# only run this workflow on commits to the main branch
on:
  push:
    branches:
      - 'main'
jobs:
  TerraformApply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Authenticate to AWS using OIDC
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          # Specify the IAM role to assume here
          role-to-assume: arn:aws:iam::662829279164:role/GitHubActionsTerraformRole
          aws-region: us-east-1
          audience: sts.amazonaws.com
      # Run Terraform using Hashicorp's setup-terraform Action
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.0
          terraform_wrapper: false
      - run:  |
          terraform init
          terraform apply -auto-approve


